<a href="https://colab.research.google.com/github/bhatturvashi2618-sketch/capstoneproject2/blob/main/loan_approval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Business Understanding
## Project Overview

Banks need to identify customers who are likely to default on loans before approval. Incorrect lending decisions can lead to financial losses. The goal of this project is to build a machine learning model that predicts loan default using customer and loan information, helping banks reduce risk and make better lending decisions.

## Problem Statement

Develop a machine learning model to predict whether a loan applicant is likely to default based on historical customer and loan data.

##Objective

Predict loan default.
Reduce financial losses.
Support better loan approval decisions.

![](https://raw.githubusercontent.com/bhatturvashi2618-sketch/capstoneproject2/main/loanapproval.png)

**Import Libraries**

In [4]:
#Data Manipulation
import pandas as pd
import numpy as np

In [5]:
#Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
#Ignore Warnings
import warnings
warnings.filterwarnings('ignore')

In [7]:
#Data Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [8]:
#Handle Missing Values
from sklearn.impute import SimpleImputer

In [3]:
!pip install xgboost
#Machine Learning Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [9]:
#Model Evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

In [10]:
#Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

In [11]:
#Cross Validation
from sklearn.model_selection import cross_val_score

In [12]:
#Feature Importance
from sklearn.inspection import permutation_importance

In [13]:
#Explainable AI (Optional but Recommended)
import shap

In [14]:
#Save the Model
import joblib

#Data Source

The dataset used in this project was obtained from Kaggle. It is a publicly available Loan Approval Prediction dataset provided in CSV format.
The data was imported into Python using the Pandas library for preprocessing, exploratory data analysis, and machine learning model development.

#Constraints

The dataset contains missing values that require preprocessing.
Some categorical features must be encoded before model training.
The dataset is relatively small, so careful validation is needed to avoid overfitting.
The data is intended for educational and research purposes and may not fully represent real-world banking scenarios.

In [17]:
accepted_df = pd.read_csv('/content/sample_data/accepted_2007_to_2018Q4.csv')
display(accepted_df.head())

rejected_df = pd.read_csv('/content/sample_data/rejected_2007_to_2018Q4.csv')
display(rejected_df.head())

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
0,1000.0,2007-05-26,Wedding Covered but No Honeymoon,693.0,10%,481xx,NM,4 years,0.0
1,1000.0,2007-05-26,Consolidating Debt,703.0,10%,010xx,MA,< 1 year,0.0
2,11000.0,2007-05-27,Want to consolidate my debt,715.0,10%,212xx,MD,1 year,0.0
3,6000.0,2007-05-27,waksman,698.0,38.64%,017xx,MA,< 1 year,0.0
4,1500.0,2007-05-27,mdrigo,509.0,9.43%,209xx,MD,< 1 year,0.0

#Data Dictionary
The dataset contains over 140 features, including borrower demographics, employment information, loan details, credit history, repayment records, and account balances. For brevity, only the key variables used in model development are described in this report.

#Exploratory Data Analysis (EDA) & Preprocessing